
project_id = "tgfnznsvscgvlcizcfzw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_email_change_enabled = true
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false

[db]
port = 54322

[studio]
enabled = true
port = 54323

[edge_runtime]
enabled = true
port = 54325

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.export-sales-report]
verify_jwt = true

[functions.export-user-data]
verify_jwt = true

[functions.manage-users]
verify_jwt = true

[functions.reset-password]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false
